### ISSUE TITLE
Is there any document?

### ISSUE THREAD

**Issue by USTfgaoaa** [carlosluisg/dec_SQP#1]
Dear sir,

Thank you for sharing your code.  Could you please provide a simple doc about how to use this repo?

**Comment by carlosluis** [comment]
Hi,

Thanks for your interest. I plan to update the readme with more instructions in the future, however right now I have my hands full with other projects.

To start using this repo I can at least point you to the "main" files you could execute to test the different algorithms.

cupSCP -> Execute the script cup-SCP/cupSCP.m
dec-iSCP -> Execute the script dec-iSCP/decSCP.m
DMPC -> Execute the script dmpc/matlab/dmpc_soft_bound2.m

In each of those scripts you can modify the characteristics of the agents (max acceleration, collision radius), as well as the transition task itself (number of agents, initial and final positions, etc.).  In each script the first block those all the configurations, the second block executes the algorithms and the third block allows you to visualize the resulting trajectories.

For DMPC there's also a CPP library although that one requires you to correctly setup several QP solver libraries: eigen-quadprog (easiest to set up), OOQP and CPLEX. You can probably modify the CMakelist to just use one of those solvers. In the future I'll make it more customizable on that sense.

Hope that helps

**Comment by USTfgaoaa** [comment]
@carlosluisg Thanks a lot !
